project:
  type: book
  output-dir: docs
  
book:
  title: "Statistical Programming"
  subtitle: "Beyond the Numbers"
  author: "Oliver Schabenberger"
  date: "8/02/2024"
  reader-mode: true

  page-footer:
    left: |
      Statistical Programming by Oliver Schabenberger
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: SPCover.png

  chapters:
    - index.qmd
    - intro.qmd
    - getting_started.qmd
    - reading_data.qmd
    - wrangling_data.qmd
    - featproc.qmd
    - summarization.qmd
    - visualization.qmd
    - matrices.qmd
    - random.qmd
    - debugging.qmd 
    - parallel.qmd
    - reproducibility.qmd
    - irls_literate.qmd
    - latex_basics.qmd
    - sql_basics.qmd
    - references.qmd
    
bibliography: sp_references.bib

format:
  html:
    theme:
        light: [cosmo,customstyle.scss]
        dark: [slate,customstyle.scss]
    smooth-scroll: true
    number-sections: true
    number-depth: 2
    toc-depth: 4
    toc-expand: 2
    pdf:
    documentclass: scrreprt

# editor: visual
