# References {.unnumbered}

::: {#refs}

@book{Baumer_etal,
title={Modern Data Science with R, 2nd ed.},
author={Baumer, Benjamin S. and Kaplan,. Daniel T., and Horton, Nicholas J.},
publisher={Chapman \& Hall/CRC Press},
year={2021},
url={https://mdsr-book.github.io/mdsr3e/}
}

@artilce{Borne_2021_profiling,
title={Data Profiling--Having that First Date with your Data},
author={Borne, Kirk},
journal={Medium},
year={2021},
issue-date={September 12, 2021},
url={https://medium.com/codex/data-profiling-having-that-first-date-with-your-data-2e05de50fca7}
}


@article{BoxCox1964,
 ISSN = {00359246},
 URL = {http://www.jstor.org/stable/2984418},
 abstract = {In the analysis of data it is often assumed that observations y1, y2, ..., yn are independently normally distributed with constant variance and with expectations specified by a model linear in a set of parameters θ. In this paper we make the less restrictive assumption that such a normal, homoscedastic, linear model is appropriate after some suitable transformation has been applied to the y's. Inferences about the transformation and about the parameters of the linear model are made by computing the likelihood function and the relevant posterior distribution. The contributions of normality, homoscedasticity and additivity to the transformation are separated. The relation of the present methods to earlier procedures for finding transformations is discussed. The methods are illustrated with examples.},
 author = {G. E. P. Box and D. R. Cox},
 journal = {Journal of the Royal Statistical Society. Series B (Methodological)},
 number = {2},
 pages = {211--252},
 publisher = {[Royal Statistical Society, Wiley]},
 title = {An Analysis of Transformations},
 urldate = {2024-06-05},
 volume = {26},
 year = {1964}
}

@book{BoxJenkins,
title={Time Series Analysis, Forecasting and Control. 3rd. ed.},
author={Box, G.E.P. and jenkins, G.M. and Reinsel, G.C.},
year={1976},
publisher={Holden-Day}
}

@article{BoxMuller1958,
title={A note on the generation of normal random deviates},
author={Box, G.E.P. and Muller, M.E.},
journal={Annals of Mathematical Statistics},
year={1958},
volume={29},
pages={610--611},
url={doi:10.1214/aoms/1177706645}
}

@book{Chang_2018,
title={R Graphics Cookbook: Practical Recipes for Visualizing Data, 2nd ed.},
author={Chang, Winston},
publisher={O'Reilly Media},
year={2018},
url={https://r-graphics.org/}
}

@article{GelmanUnwin2013,
title={Infovis and Statistical Graphics: Different Goals, Different Looks},
url={https://www.tandfonline.com/doi/full/10.1080/10618600.2012.761137}, 
author={Gelman, A., and Unwin, A.},
journal={Journal of Computational and Graphical Statistics}, 
volume={22}, 
year={2013},
issue={1},
pages={2--28}
}

@article{Knuth1984,
    author = {Knuth, D. E.},
    title = "{Literate Programming}",
    journal = {The Computer Journal},
    volume = {27},
    number = {2},
    pages = {97-111},
    year = {1984},
    month = {01},
    abstract = "{The author and his associates have been experimenting for the past several years with a programming language and documentation system called WEB. This paper presents WEB by example, and discusses why the new system appears to be an improvement over previous ones.}",
    issn = {0010-4620},
    doi = {10.1093/comjnl/27.2.97},
    url = {https://doi.org/10.1093/comjnl/27.2.97},
    eprint = {https://academic.oup.com/comjnl/article-pdf/27/2/97/981657/270097.pdf},
}

@article{Matsumoto1998,
title={ Mersenne Twister: A 623-dimensionally equidistributed uniform pseudo-random number generator},
author={Matsumoto, M. and Nishimura, T.},
journal={ACM Transactions on Modeling and Computer Simulation},
year={1998},
volume={8},
pages={3--30}
}

@book{McCullaghNelder,
title={Generalized Linear Models, 2nd ed.},
author={McCullagh, P. and Nelder Frs, J.A.},
year={1989},
publisher={Chapman \& Hall, New York}
}

@book{McKinney_PDA,
title={Python for Data Analysis: Data Wrangling with pandas, NumPy and Jupyter, 3rd ed.},
author={McKinney, Wes},
publisher={O'Reilly Media},
year={2022},
url={https://wesmckinney.com/book/}
}

@book{Pengetal2020,
title={Mastering Software Development in R},
author={Peng, Roger D. and Kross, Sean and Anderson, Brooke},
year={2020},
url={https://bookdown.org/rdpeng/RProgDA/}
}

@book{Schabenberger2001,
title={Contemporary Statistical Models for the Plant and Soil Sciences},
author={Schabenberger, O. and Pierce, Francis J.},
year={2001},
publisher={CRC Press, Boca Raton}
}

@book{Tufte_1983,
title={The Visual Display of Quantitative Information}, 
author={Tufte, E.},
year={1983},
publisher={Graphics Press}
}

@book{Tufte_2001,
title={The Visual Display of Quantitative Information, 2nd ed.}, 
author={Tufte, E.},
year={2001},
publisher={Graphics Press}
}

@article{Tukey1993,
 ISSN = {10618600},
 URL = {http://www.jstor.org/stable/1390951},
 author = {John W. Tukey},
 journal = {Journal of Computational and Graphical Statistics},
 number = {1},
 pages = {1--33},
 publisher = {[American Statistical Association, Taylor & Francis, Ltd., Institute of Mathematical Statistics, Interface Foundation of America]},
 title = {Graphic Comparisons of Several Linked Aspects: Alternatives and Suggested Principles},
 urldate = {2024-07-30},
 volume = {2},
 year = {1993}
}

@book{VanderPlas,
title={Python Data Science Handbook},
author={VanderPlas, J.},
publisher={O'Reilly Media},
year={2016},
url={https://jakevdp.github.io/PythonDataScienceHandbook/}
}

@inproceedings{Vaswani_etal_2017,
author = {Vaswani, Ashish and Shazeer, Noam and Parmar, Niki and Uszkoreit, Jakob and Jones, Llion and Gomez, Aidan N. and Kaiser, \L{}ukasz and Polosukhin, Illia},
title = {Attention is all you need},
year = {2017},
publisher = {Curran Associates Inc.},
address = {Red Hook, NY, USA},
booktitle = {Proceedings of the 31st International Conference on Neural Information Processing Systems},
pages = {6000–6010},
numpages = {11},
location = {Long Beach, California, USA},
series = {NIPS'17}
}

@book{Wickham_AdvR,
title={Advanced R, 2nd ed.},
author={Wickham, H.},
publisher={Chapman \& Hall/CRC Press},
year={2019},
url={http://adv-r.had.co.nz/}
}

@book{Wickham_RDS,
title={R for Data Science: Import, Tidy, Transform, Visualize, and Model Data, 2nd ed.},
author={Wickham, H. and Cetinkaya-Rundel, M., and Grolemund, G.},
publisher={O'Reilly Media},
year={2023},
url={https://r4ds.hadley.nz/}
}

@book{Wilke2019,
author={Wilke, Claus O.},
title={Fundamentals of Data Visualization},
publisher={O'Reilly Media},
url={https://clauswilke.com/dataviz/},
year={2019}
}

@book{Xie_etal,
title={R Markdown: The Definite Guide},
author={Xie, Yihui and Allaire, J.J. and Grolemund, Garrett},
publisher={Chapman \& Hall/CRC Press},
year={2019},
url={https://bookdown.org/yihui/rmarkdown/}
}

@book{Xie_Cookbook,
title={R Markdown Cookbook},
author={Xie, Yihui and Dervieux, Christophe, and Riederer, Emily},
publisher={Chapman \& Hall/CRC Press},
year={2021},
url={https://bookdown.org/yihui/rmarkdown-cookbook/}
}

@article{YeoJohnson2000,
    author = {Yeo, In‐Kwon and Johnson, Richard A.},
    title = "{A new family of power transformations to improve normality or symmetry}",
    journal = {Biometrika},
    volume = {87},
    number = {4},
    pages = {954-959},
    year = {2000},
    month = {12},
    issn = {0006-3444},
    doi = {10.1093/biomet/87.4.954},
    url = {https://doi.org/10.1093/biomet/87.4.954},
    eprint = {https://academic.oup.com/biomet/article-pdf/87/4/954/633221/870954.pdf},
}


:::

