<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.552">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistical Programming - 5&nbsp; Feature and Target Processing</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./summarization.html" rel="next">
<link href="./wrangling_data.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./featproc.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Feature and Target Processing</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical Programming</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./getting_started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Getting Started</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reading_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Reading Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./wrangling_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Wrangling Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./featproc.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Feature and Target Processing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summarization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summarization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./matrices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Vectors and Matrices</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./random.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Random Numbers</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./debugging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Debugging in <code>R</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reproducibility.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Reproducible Research and Data Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./irls_literate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Iteratively Reweighted Least Squares</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./latex_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title"><span class="math inline">\(\LaTeX\)</span> Basics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sql_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">SQL Basics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#standardization" id="toc-standardization" class="nav-link active" data-scroll-target="#standardization"><span class="header-section-number">5.1</span> Standardization</a>
  <ul>
  <li><a href="#centering-and-scaling" id="toc-centering-and-scaling" class="nav-link" data-scroll-target="#centering-and-scaling">Centering and Scaling</a></li>
  <li><a href="#range-scaling" id="toc-range-scaling" class="nav-link" data-scroll-target="#range-scaling">Range Scaling</a></li>
  <li><a href="#to-scale-or-not-to-scale" id="toc-to-scale-or-not-to-scale" class="nav-link" data-scroll-target="#to-scale-or-not-to-scale">To Scale or not to Scale</a></li>
  <li><a href="#using-the-caret-package" id="toc-using-the-caret-package" class="nav-link" data-scroll-target="#using-the-caret-package">Using the <code>caret</code> package</a></li>
  </ul></li>
  <li><a href="#normalization" id="toc-normalization" class="nav-link" data-scroll-target="#normalization"><span class="header-section-number">5.2</span> Normalization</a></li>
  <li><a href="#sec-encoding" id="toc-sec-encoding" class="nav-link" data-scroll-target="#sec-encoding"><span class="header-section-number">5.3</span> Encoding</a>
  <ul>
  <li><a href="#sec-encoding-factors" id="toc-sec-encoding-factors" class="nav-link" data-scroll-target="#sec-encoding-factors">Factor Variables</a>
  <ul class="collapse">
  <li><a href="#one-hot-encoding" id="toc-one-hot-encoding" class="nav-link" data-scroll-target="#one-hot-encoding">One-hot encoding</a></li>
  <li><a href="#average-effect-encoding" id="toc-average-effect-encoding" class="nav-link" data-scroll-target="#average-effect-encoding">Average effect encoding</a></li>
  <li><a href="#baseline-encoding" id="toc-baseline-encoding" class="nav-link" data-scroll-target="#baseline-encoding">Baseline encoding</a></li>
  </ul></li>
  <li><a href="#continuous-variables" id="toc-continuous-variables" class="nav-link" data-scroll-target="#continuous-variables">Continuous Variables</a></li>
  </ul></li>
  <li><a href="#transforming-the-target" id="toc-transforming-the-target" class="nav-link" data-scroll-target="#transforming-the-target"><span class="header-section-number">5.4</span> Transforming the Target</a>
  <ul>
  <li><a href="#discretizing" id="toc-discretizing" class="nav-link" data-scroll-target="#discretizing">Discretizing</a></li>
  <li><a href="#nonlinear-transformations" id="toc-nonlinear-transformations" class="nav-link" data-scroll-target="#nonlinear-transformations">Nonlinear Transformations</a>
  <ul class="collapse">
  <li><a href="#box-cox-family" id="toc-box-cox-family" class="nav-link" data-scroll-target="#box-cox-family">Box-Cox family</a></li>
  <li><a href="#quantile-transformation" id="toc-quantile-transformation" class="nav-link" data-scroll-target="#quantile-transformation">Quantile transformation</a></li>
  <li><a href="#to-transform-or-not-to-transform" id="toc-to-transform-or-not-to-transform" class="nav-link" data-scroll-target="#to-transform-or-not-to-transform">To Transform or not to Transform</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-feat-processing" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Feature and Target Processing</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Wrangling data organizes the data in a form that is suitable for statistical analysis. After wrangling, the data is usually in a rectangular form, each observation in a separate row, each variable in a separate column.</p>
<p>While the data might have the right <em>shape</em>, the variables might not have the right <em>content</em>. Feature and target processing falls under the umbrella of <strong>preprocessing</strong> data, but now the focus is on transforming the data into a form suitable for analytic models–processing the data before it is consumed by a model.</p>
<p>To make the difference between processing for data quality and feature processing explicit, consider the data in <a href="#tbl-city-data" class="quarto-xref">Table&nbsp;<span>5.1</span></a>.</p>
<div id="tbl-city-data" class="striped quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-city-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.1: City names before and after data processing for quality.
</figcaption>
<div aria-describedby="tbl-city-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table">
<thead>
<tr class="header">
<th style="text-align: left;">Before Processing</th>
<th style="text-align: left;">After Processing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">New York</td>
<td style="text-align: left;">New York</td>
</tr>
<tr class="even">
<td style="text-align: left;">NY</td>
<td style="text-align: left;">New York</td>
</tr>
<tr class="odd">
<td style="text-align: left;">new York</td>
<td style="text-align: left;">New York</td>
</tr>
<tr class="even">
<td style="text-align: left;">LA</td>
<td style="text-align: left;">Los Angeles</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LAX</td>
<td style="text-align: left;">Los Angeles</td>
</tr>
<tr class="even">
<td style="text-align: left;">Los Ang.</td>
<td style="text-align: left;">Los Angeles</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chicago</td>
<td style="text-align: left;">Chicago</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chicago, Ill.</td>
<td style="text-align: left;">Chicago</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Data quality ensures that city names are consistent in the data set. Feature processing transforms the corrected city names into a numerical representation for analytic processing.</p>
<p>Preprocessing data for modeling applies to the target variable and the input variables. For example, one-hot encoding of categorical variables is used to represent categorical input variables as multiple dummy variables on the right hand side of the model. It is also used to encode categorical target variables for classification models.</p>
<section id="standardization" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="standardization"><span class="header-section-number">5.1</span> Standardization</h2>
<section id="centering-and-scaling" class="level3">
<h3 class="anchored" data-anchor-id="centering-and-scaling">Centering and Scaling</h3>
<p>Standardizing a variable <span class="math inline">\(X\)</span> comprises two steps, <strong>centering</strong> and <strong>scaling</strong>. Scaling does what it says, it replaces <span class="math inline">\(x_i\)</span> with <span class="math inline">\(c\times x_i\)</span> where <span class="math inline">\(c\)</span> is the scaling factor. Centering means shifting the variable so that it is centered at some specific value. The common parameters of standardization are centering at the mean <span class="math inline">\(\overline{y}\)</span> and scaling with the standard deviation <span class="math inline">\(s_x\)</span>: <span class="math display">\[
z = \frac{x-\overline{x}}{s_x}
\]</span> The transformed variable has a sample mean of 0 and a sample standard deviation of 1: <span class="math display">\[
\overline{z} = 0 \qquad s_z = 1
\]</span> <a href="#fig-gamma-standardized" class="quarto-xref">Figure&nbsp;<span>5.1</span></a> shows the effect of standardization of 1,000 observations drawn from a Gamma(3,2) distribution. Centering shifts the data to have mean zero and compresses the dispersion of the data to a standard deviation of one. The general shape of the distribution is preserved.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">543</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(<span class="dv">1000</span>,<span class="at">shape=</span><span class="dv">3</span>,<span class="at">scale=</span><span class="dv">2</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>x_scaled <span class="ot">&lt;-</span> <span class="fu">scale</span>(x)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.793267</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.289989</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">mean</span>(x_scaled),<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">sd</span>(x_scaled),<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(x,<span class="at">main=</span><span class="st">"Original"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(x_scaled, <span class="at">main=</span><span class="st">"Scaled"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-gamma-standardized" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gamma-standardized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="featproc_files/figure-html/fig-gamma-standardized-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gamma-standardized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: Original and standardized data drawn from a Gamma(3,2) distribution.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The mean (center) of the original data is 5.7933 and the standard deviation is 3.29. The <code>scale</code> function centers and scales the data by default, using the mean and the standard deviation. If you call <code>scale</code> without centering, <code>scale(x,center=FALSE)</code>, the data will be scaled by the root mean square error, <span class="math display">\[
\sqrt{\frac{\sum_{i=1}^n x_i^2}{n-1}}
\]</span> This is not the standard deviation of <span class="math inline">\(x\)</span>. If you wish to scale with the standard deviation without centering, pass the desired value for the <code>scale=</code> parameter:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>x_notcentered_but_scaled_with_sd <span class="ot">&lt;-</span> <span class="fu">scale</span>(x,<span class="at">center=</span><span class="cn">FALSE</span>,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">scale=</span><span class="fu">sd</span>(x))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x_notcentered_but_scaled_with_sd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.760877</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(x_notcentered_but_scaled_with_sd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Scaling called Standardization">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Scaling called Standardization
</div>
</div>
<div class="callout-body-container callout-body">
<p>You will find references in the literature and in software documentation to “scaling the data”. It is often understood as standardization of the data, that is, centering <strong>and</strong> scaling.</p>
<p>Be also aware of the default behavior of software packages. The <code>prcomp</code> function for principal component analysis in <code>R</code>, for example, centers the data by default but does not scale by default. The <code>loess</code> function in <code>R</code> normalizes the predictor variables, using scaling to a robust estimate of the standard deviation, but only if there is more than one predictor. The <code>glmnet::glmnet</code> function standardizes the inputs by default (<code>standardize=TRUE</code>) and reports the results on the original scale of the predictors.</p>
</div>
</div>
</section>
<section id="range-scaling" class="level3">
<h3 class="anchored" data-anchor-id="range-scaling">Range Scaling</h3>
<p>This form of standardizing of the data scales the data so it falls between a known lower and upper bound, often 0 and 1. Suppose <span class="math inline">\(Z\)</span> is a range-scaled version of <span class="math inline">\(X\)</span> such that <span class="math inline">\(z_{\text{min}} \le z \le z_{\text{max}}\)</span>. <span class="math inline">\(Z\)</span> can be computed by scaling and shifting a standardized form of <span class="math inline">\(X\)</span>: <span id="eq-range-scaling"><span class="math display">\[
\begin{align*}
  x^* &amp;= \frac{x-\min(x)}{\max(x)-\min(x)} \\
  z &amp;= z_{\text{min}} + x^* \times (z_{\text{max}} - z_{\text{min}})
\end{align*}
\tag{5.1}\]</span></span></p>
<p>To rescale data in <code>R</code> you can use the <code>rescale</code> function in the <code>scales</code> package or the <code>preProcess</code> function in the <code>caret</code> package. The <code>scales</code> package was developed to support data transformations for visualizations. The <code>caret</code> package is a comprehensive collection of functions that support the training and testing of many statistical and machine learning models.</p>
<p>Alternatively, you can write a function to do that. This is a good opportunity to write a function that performs pretty simple math. However, a lot goes into writing a function that does so in a robust manner. There are many ways in which the simple calculation in <a href="#eq-range-scaling" class="quarto-xref">Equation&nbsp;<span>5.1</span></a> can go wrong:</p>
<ul>
<li><code>x</code> as passed to the function contains missing values</li>
<li><code>x</code> as passed to the function is not of numeric type</li>
<li><code>x</code> is a vector of constants (cannot divide by <span class="math inline">\(\max(x)-\min(x)\)</span>)</li>
<li>The caller specifies <span class="math inline">\(z_{\text{max}}\)</span> and <span class="math inline">\(z_{\text{min}}\)</span> in the wrong order</li>
<li>The caller specifies <span class="math inline">\(z_{\text{max}} = z_{\text{min}}\)</span></li>
</ul>
<p>The following code writes a function that handles these cases and scales the Gamma(3,2) data to lie between 1 and 2.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>range_scale <span class="ot">&lt;-</span> <span class="cf">function</span>(x,<span class="at">low=</span><span class="dv">0</span>,<span class="at">hi=</span><span class="dv">1</span>) {</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(x) <span class="sc">&amp;&amp;</span> <span class="fu">is.numeric</span>(x)) {</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>        minval <span class="ot">&lt;-</span> <span class="fu">min</span>(x,<span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>        maxval <span class="ot">&lt;-</span> <span class="fu">max</span>(x,<span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> (maxval<span class="sc">-</span>minval <span class="sc">&lt;</span> <span class="fl">1e-10</span>) {</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">warning</span>(<span class="st">"No rescaling done due to small range of data."</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">return</span> (x)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.numeric</span>(x)) <span class="fu">warning</span>(<span class="st">"Cannot rescale non-numeric data."</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>        <span class="fu">return</span> (<span class="cn">NULL</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (low <span class="sc">&gt;</span> hi) {</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>        lowbound <span class="ot">&lt;-</span> hi</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>        hibound  <span class="ot">&lt;-</span> low</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>        <span class="fu">message</span>(<span class="st">"Switching hi and low values."</span>)</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> <span class="cf">if</span> (low<span class="sc">==</span>hi) {</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>        <span class="fu">return</span> (<span class="fu">rep</span>(low,<span class="fu">length</span>(x)))</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>        lowbound <span class="ot">&lt;-</span> low</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>        hibound <span class="ot">&lt;-</span> hi</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> ((lowbound<span class="sc">==</span><span class="dv">0</span>) <span class="sc">&amp;</span> (hibound<span class="sc">==</span><span class="dv">1</span>)) {</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>        <span class="fu">return</span> ( (x<span class="sc">-</span>minval)<span class="sc">/</span>(maxval<span class="sc">-</span>minval) )</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {</span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>        <span class="fu">return</span> (lowbound <span class="sc">+</span> (x<span class="sc">-</span>minval)<span class="sc">/</span>(maxval<span class="sc">-</span>minval) <span class="sc">*</span> (hibound<span class="sc">-</span>lowbound))</span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>x_rs <span class="ot">&lt;-</span> <span class="fu">range_scale</span>(x,<span class="dv">1</span>,<span class="dv">2</span>)</span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(x_rs, <span class="at">main=</span><span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-gamma-range-scaled" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gamma-range-scaled-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="featproc_files/figure-html/fig-gamma-range-scaled-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gamma-range-scaled-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: Sample from Gamma(3,2) distribution scaled to [0,2].
</figcaption>
</figure>
</div>
</div>
</div>
<p>Most lines of code in function <code>range_scale</code> are dedicated to handling bad inputs and boundary cases. That is not unusual in writing robust code.</p>
<hr>
<p>An advantage of range scaling is that the same range can be applied to training and test data. This makes it easy to process test data prior to applying a model derived from range-scaled data.</p>
</section>
<section id="to-scale-or-not-to-scale" class="level3">
<h3 class="anchored" data-anchor-id="to-scale-or-not-to-scale">To Scale or not to Scale</h3>
<p>Some data scientists standardize the data by default. When should you standardize and when should you not? Analytic techniques that depend on measures of distance to express similarity or dissimilarity between observations, or that depend on partitioning variability, typically benefit from standardized input variables.</p>
<p>Examples of the former group are <span class="math inline">\(K\)</span>-means clustering and hierarchical clustering. Here, the data are grouped into clusters based on their similarity, which is expressed as a function of a distance measure. Without scaling the data, large items tend to be further apart than small items, distorting the analysis toward inputs with large scale. Whether lengths are measured in meters, centimeters, or inches should not affect the analysis. Principal component analysis (PCA) is an example of a method in the second group, apportioning variability to linear combinations of the input variables. Without scaling, inputs that have a large variance can dominate the PCA to the point of not being interpretable or meaningful. Larger things tend to have larger variability compared to small things.</p>
<p>Binary variables, are usually not scaled. This includes variables derived from encoding factor variables, see <a href="#sec-encoding-factors" class="quarto-xref"><span>Section 5.3.1</span></a>.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Train and Test Data">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Train and Test Data
</div>
</div>
<div class="callout-body-container callout-body">
<p>Any preprocessing steps such as standardization, scaling, normalization, are applied <strong>separately</strong> to train and test data set. In the case of standardization, for example, it means that you split the data into train and test data sets first, then standardize each separately. The training data set is centered and scaled by the means and sample standard deviations in the training data set. The test data set is centered and scaled by the means and standard deviations in the test data set. Both data sets thus have the same properties of zero mean and standard deviation one.</p>
<p>If we were to standardize first and split into training and test data set second, neither data set would have zero mean and unit standard deviation. Furthermore, information from the training data (the mean and standard deviation) would <strong>leak</strong> into the test data set.</p>
</div>
</div>
</section>
<section id="using-the-caret-package" class="level3">
<h3 class="anchored" data-anchor-id="using-the-caret-package">Using the <code>caret</code> package</h3>
<p>The <code>caret</code> package supports standardization and other transformations through the <code>preProcess</code> function. It can operate on all columns of a matrix or data frame, ignoring non-numerical columns. You pass the return object from <code>preProcess</code> to the <code>predict</code> function to generate a data frame from an input data frame.</p>
<p>The following code creates a centered and scaled version of the <code>iris</code> data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>iris_sc <span class="ot">&lt;-</span> <span class="fu">preProcess</span>(iris,<span class="at">method=</span><span class="fu">c</span>(<span class="st">"center"</span>,<span class="st">"scale"</span>))</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>iris_sc_data <span class="ot">&lt;-</span> <span class="fu">predict</span>(iris_sc,iris)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(iris_sc_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1   -0.8976739  1.01560199    -1.335752   -1.311052  setosa
2   -1.1392005 -0.13153881    -1.335752   -1.311052  setosa
3   -1.3807271  0.32731751    -1.392399   -1.311052  setosa
4   -1.5014904  0.09788935    -1.279104   -1.311052  setosa
5   -1.0184372  1.24503015    -1.335752   -1.311052  setosa
6   -0.5353840  1.93331463    -1.165809   -1.048667  setosa</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">apply</span>(iris_sc_data[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>],<span class="dv">2</span>,mean),<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
           0            0            0            0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(iris_sc_data[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>],<span class="dv">2</span>,sd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
           1            1            1            1 </code></pre>
</div>
</div>
<p>This does not seem to buy you much over using <code>scale()</code>, but the return object from <code>preProcess</code> is worth checking out with <code>str(iris_sc)</code>. It contains a lot of good information about the input data frame or matrix. We’ll use <code>preProcess</code> again below to perform the nonlinear Box-Cox transformation.</p>
<p>The following code applies range scaling to the <code>iris</code> data set, scaling all numeric variables to fall in the [1,5] interval.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>iris_range <span class="ot">&lt;-</span> <span class="fu">preProcess</span>(iris,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">method=</span><span class="fu">c</span>(<span class="st">"range"</span>),</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">rangeBounds=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">5</span>))</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>iris_range_data <span class="ot">&lt;-</span> <span class="fu">predict</span>(iris_range,iris)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(iris_range_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1     1.888889    3.500000     1.271186    1.166667  setosa
2     1.666667    2.666667     1.271186    1.166667  setosa
3     1.444444    3.000000     1.203390    1.166667  setosa
4     1.333333    2.833333     1.338983    1.166667  setosa
5     1.777778    3.666667     1.271186    1.166667  setosa
6     2.222222    4.166667     1.474576    1.500000  setosa</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(iris_range_data[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>],<span class="dv">2</span>,min)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
           1            1            1            1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(iris_range_data[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>],<span class="dv">2</span>,max)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
           5            5            5            5 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(iris_range_data[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>],<span class="dv">2</span>,mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
    2.714815     2.762222     2.869831     2.832222 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(iris_range_data[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>],<span class="dv">2</span>,sd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
   0.9200735    0.7264438    1.1968124    1.2703961 </code></pre>
</div>
</div>
</section>
</section>
<section id="normalization" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="normalization"><span class="header-section-number">5.2</span> Normalization</h2>
<p>Normalization is sometimes (often, actually) described as a transformation of data to normality; the transformed data appears Gaussian distributed. This is <strong>not</strong> what we consider normalization here. A variable <span class="math inline">\(z\)</span> that is normalized with respect to the <span class="math inline">\(L_2\)</span> norm has the property <span class="math display">\[
||\textbf{z}|| = \sqrt{\sum_{i=1}^n z_i^2}  = 1
\]</span></p>
<p>A variable <span class="math inline">\(x\)</span> can be normalized with respect to any norm by dividing each value by the norm of the vector. In the case of <span class="math inline">\(L_2\)</span>, <span class="math display">\[
z_i = \frac{x_i}{||\textbf{x}||}
\]</span></p>
<p>Normalization is a special case of scaling so that the resulting vector has unit length with respect to some norm. Any norm can be used to normalize the data, for example, the <span class="math inline">\(L_1\)</span> norm <span class="math inline">\(|\textbf{x}|\)</span>. Note that scaling by the standard deviation does not yield a vector with unit length, but a vector with unit standard deviation.</p>
<p>The following code normalizes the Gamma(3,2) sample with respect to <span class="math inline">\(L_2\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>norm_l2 <span class="ot">&lt;-</span> <span class="fu">norm</span>(<span class="fu">as.matrix</span>(x),<span class="at">type=</span><span class="st">"2"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>x_norm_l2 <span class="ot">&lt;-</span> x<span class="sc">/</span>norm_l2</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Check, the normalized vector should have L2-norm of 1</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">norm</span>(x_norm_l2,<span class="at">type=</span><span class="st">"2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(x_norm_l2, <span class="at">main=</span><span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-gamma-normalized" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gamma-normalized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="featproc_files/figure-html/fig-gamma-normalized-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gamma-normalized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.3: Normalized data from the Gamma(3,2) distribution.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Normalization of the sample from the Gamma(3,2) distribution maintains the general shape of the distribution and changes its scale (<a href="#fig-gamma-normalized" class="quarto-xref">Figure&nbsp;<span>5.3</span></a>).</p>
</section>
<section id="sec-encoding" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="sec-encoding"><span class="header-section-number">5.3</span> Encoding</h2>
<p>Data processed by algorithms are represented as numbers, integers and real numbers. The information we collect is often not in the form that can be directly processed by a data science algorithm. Treatments in an experiment could be identified with numeric values, “1”, “2”, “3”, etc. We need to somehow tell the algorithm that these are simply identifying <strong>labels</strong> and should not be treated as numbers for which differences are meaningful. Treatment “2” is simply different from treatment “1”, it is not necessarily twice as much as treatment “1”. Whether the treatments are labeled “1”, “2”, “3”, or “A”, “B”, “C”, the same analysis must result.</p>
<p>Many pieces of information come to us as in the form of character strings, either as structured or as unstructured text. A case of structured text data is when we use strings as labels for things. The treatment labels “A”, “B”, “C” are an example. An example of unstructured text is free-form text such as the quote</p>
<blockquote class="blockquote">
<p><em>The strength of a bureaucracy is measured by its ability to resist change.</em></p>
</blockquote>
<p>An algorithm that predicts the sentiment of the quote must translate these characters into a numerical representation. The process of transforming data from a human-readable form into a machine-readable form is known as <strong>encoding</strong> in machine learning. The reverse, translating from a machine-readable to a human-readable representation is known as <strong>decoding</strong>.</p>
<p>In this section we take a somewhat broader view of data encoding.</p>
<div class="definition">
<div class="definition-header">
<p>Definition: Data Encoding and Decoding</p>
</div>
<div class="definition-container">
<p>Encoding of data is the process of translating information into a numerical format for processing by a statistical or machine learning algorithm.</p>
<p>Decoding is translating information from the numerical format used in analytic processing back into human-readable form.</p>
</div>
</div>
<p>Encoding is more important to us at this stage. When dealing with natural language processing tasks such as sequence-to-sequence modeling, encoding and decoding are important. An example is the translation of text from one language into another using artificiall neural networks. The input text is encoded into numeric format, processed by a network, and the output of that network is decoded by another network into the target language of translation.</p>
<section id="sec-encoding-factors" class="level3">
<h3 class="anchored" data-anchor-id="sec-encoding-factors">Factor Variables</h3>
<p>The first case of encoding information is the processing of <strong>factor</strong> input variables. Factors are categorical variables representing <strong>levels</strong> (or classes, or categories, or states). For example, the variable <code>treatment</code> with levels “A”, “B”, and “C” is a three-level factor variable. When this variable is used in a statistical model, it enters the model through its levels, not through its values. That is why some software refers to the process of encoding factor variables as <em>levelization</em>.</p>
<p>To encode factor variables, three decisions affect the representation of the variable and the interpretation of the results:</p>
<ol type="1">
<li>The order of the levels</li>
<li>The method of encoding</li>
<li>The choice of reference level—if any</li>
</ol>
<p>The <strong>order</strong> of the levels is important because it affects the order in which the factor levels enter the model and how the <span class="math inline">\(\textbf{X}\)</span> matrix is constructed. Consider the following example, which we will use throughout this section, of two factors with 2 and 3 levels, respectively, and a numeric variable <span class="math inline">\(X\)</span>.</p>
<div id="tbl-factor-data" class="striped quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-factor-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.2: Data with two factors <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> with 2 and 3 levels, respectively, and a numeric variable. To distinguish the values of the variables from subsequent encodings, the values are shown in boldface.
</figcaption>
<div aria-describedby="tbl-factor-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table">
<thead>
<tr class="header">
<th style="text-align: center;">Y</th>
<th style="text-align: center;">A</th>
<th style="text-align: center;">B</th>
<th style="text-align: center;"><span class="math inline">\(X\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;"><strong>1</strong></td>
<td style="text-align: center;"><strong>1</strong></td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;"><strong>1</strong></td>
<td style="text-align: center;"><strong>2</strong></td>
<td style="text-align: center;">0.5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;"><strong>1</strong></td>
<td style="text-align: center;"><strong>3</strong></td>
<td style="text-align: center;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;"><strong>2</strong></td>
<td style="text-align: center;"><strong>1</strong></td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;"><strong>2</strong></td>
<td style="text-align: center;"><strong>2</strong></td>
<td style="text-align: center;">0.5</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;"><strong>2</strong></td>
<td style="text-align: center;"><strong>3</strong></td>
<td style="text-align: center;">0.25</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="one-hot-encoding" class="level4">
<h4 class="anchored" data-anchor-id="one-hot-encoding">One-hot encoding</h4>
<p>If we choose <strong>one-hot encoding</strong>, also called standard encoding or <strong>dummy encoding</strong>, then the <span class="math inline">\(k\)</span> levels of each variable are transformed into <span class="math inline">\(k\)</span> columns of 0/1 values. The value in the <span class="math inline">\(j\)</span><sup>th</sup> column is 1 if the variable is at level <span class="math inline">\(j\)</span>, 0 otherwise. The one-hot encoding for <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> in <a href="#tbl-factor-data" class="quarto-xref">Table&nbsp;<span>5.2</span></a> is shown in <a href="#tbl-factor-onehot" class="quarto-xref">Table&nbsp;<span>5.3</span></a>.</p>
<div id="tbl-factor-onehot" class="striped quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-factor-onehot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.3: One-hot encoding of <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>.
</figcaption>
<div aria-describedby="tbl-factor-onehot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table">
<thead>
<tr class="header">
<th style="text-align: right;">A</th>
<th style="text-align: right;"><span class="math inline">\(A_1\)</span></th>
<th style="text-align: right;"><span class="math inline">\(A_2\)</span></th>
<th style="text-align: right;">B</th>
<th style="text-align: right;"><span class="math inline">\(B_1\)</span></th>
<th style="text-align: right;"><span class="math inline">\(B_2\)</span></th>
<th style="text-align: right;"><span class="math inline">\(B_3\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><strong>1</strong></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;"><strong>1</strong></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>1</strong></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;"><strong>2</strong></td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>1</strong></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;"><strong>3</strong></td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>2</strong></td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"><strong>1</strong></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>2</strong></td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"><strong>2</strong></td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>2</strong></td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"><strong>3</strong></td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><span class="math inline">\(A_1\)</span> and <span class="math inline">\(A_2\)</span> are the first and second columns of the encoded 2-level factor <span class="math inline">\(A\)</span>. So why does the order in which these columns enter a statistical model matter? Suppose our model is a linear model with inputs <span class="math inline">\(X\)</span>, a numeric variable, and <span class="math inline">\(A\)</span> (<span class="math inline">\(\textbf{x} = [x, A_1, A_3]\)</span>): <span class="math display">\[
f(\textbf{x}) = \beta_0 + \beta_1x + \beta_2 A_1 + \beta_2 A_2
\]</span> For the six observations in <a href="#tbl-factor-data" class="quarto-xref">Table&nbsp;<span>5.2</span></a>, the <span class="math inline">\(\textbf{X}\)</span> matrix of the model is <span class="math display">\[
\textbf{X} = \left [\begin{array}{rrrr}
1 &amp; 1    &amp; 1 &amp; 0 \\
1 &amp; 0.5  &amp; 1 &amp; 0 \\
1 &amp; 0.25 &amp; 1 &amp; 0 \\
1 &amp; 1    &amp; 0 &amp; 1 \\
1 &amp; 0.5  &amp; 0 &amp; 1 \\
1 &amp; 0.25 &amp; 0 &amp; 1 \\
\end{array} \right]
\]</span></p>
<p>There is a problem, the first column of <span class="math inline">\(\textbf{X}\)</span> is the sum of the third and forth column. This perfect linear dependency makes the <span class="math inline">\(\textbf{X}\)</span> matrix singular, the <span class="math inline">\(\textbf{X}^\prime\textbf{X}\)</span> matrix cannot be inverted, and the ordinary least squares solution cannot be computed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>   ,<span class="dv">1</span>,<span class="dv">0</span>,</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>              <span class="dv">1</span>,<span class="fl">0.5</span> ,<span class="dv">1</span>,<span class="dv">0</span>, </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>              <span class="dv">1</span>,<span class="fl">0.25</span>,<span class="dv">1</span>,<span class="dv">0</span>,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>              <span class="dv">1</span>,<span class="dv">1</span>   ,<span class="dv">0</span>,<span class="dv">1</span>, </span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>              <span class="dv">1</span>,<span class="fl">0.5</span> ,<span class="dv">0</span>,<span class="dv">1</span>, </span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>              <span class="dv">1</span>,<span class="fl">0.25</span>,<span class="dv">0</span>,<span class="dv">1</span>),<span class="at">nrow=</span><span class="dv">6</span>,<span class="at">ncol=</span><span class="dv">4</span>,<span class="at">byrow=</span><span class="cn">TRUE</span>)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>XpX <span class="ot">&lt;-</span> <span class="fu">t</span>(X) <span class="sc">%*%</span> X</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>XpX</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]  [,2] [,3] [,4]
[1,]  6.0 3.500 3.00 3.00
[2,]  3.5 2.625 1.75 1.75
[3,]  3.0 1.750 3.00 0.00
[4,]  3.0 1.750 0.00 3.00</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">solve</span>(XpX)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in solve.default(XpX): Lapack routine dgesv: system is exactly singular: U[4,4] = 0</code></pre>
</div>
</div>
<p>To remedy this problem many software packages implicitly make one of the levels of a one-hot encoded factor a <strong>reference level</strong>. <code>R</code> takes the first level of a factor as the reference level. The following code creates a data frame from the data in <a href="#tbl-factor-data" class="quarto-xref">Table&nbsp;<span>5.2</span></a>, declares the numeric variable <code>A</code> as a factor and assigns the second level as the reference level.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">y=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>),</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">x=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="fl">0.5</span>,<span class="fl">0.25</span>,<span class="dv">1</span>,<span class="fl">0.5</span>,<span class="fl">0.25</span>),</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">A=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>A <span class="ot">&lt;-</span> <span class="fu">relevel</span>(<span class="fu">as.factor</span>(df<span class="sc">$</span>A),<span class="at">ref=</span><span class="dv">2</span>)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x <span class="sc">+</span> A, <span class="at">data=</span>df)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept)  6.500000  0.2089277  31.11124 7.296355e-05
x           -2.571429  0.2857143  -9.00000 2.895812e-03
A1          -3.000000  0.1781742 -16.83746 4.561983e-04</code></pre>
</div>
</div>
<p>The analysis now succeeds but the coefficients reported seem to be for a model without the reference level, namely <span class="math display">\[
f(\textbf{x}) = \beta_0 + \beta_1x + \beta_2 A_1
\]</span></p>
<p>You can easily verify by specifying this model directly:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">y=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>),</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">x=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="fl">0.5</span>,<span class="fl">0.25</span>,<span class="dv">1</span>,<span class="fl">0.5</span>,<span class="fl">0.25</span>),</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">A1=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>))</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x <span class="sc">+</span> A1, <span class="at">data=</span>df2)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept)  6.500000  0.2089277  31.11124 7.296355e-05
x           -2.571429  0.2857143  -9.00000 2.895812e-03
A1          -3.000000  0.1781742 -16.83746 4.561983e-04</code></pre>
</div>
</div>
<p>So where did the information about <span class="math inline">\(A_2\)</span> end up? To see how this works, consider the model formula for the cases <span class="math inline">\(A_1 = 0\)</span> and <span class="math inline">\(A_1 = 1\)</span>:</p>
<p><span class="math display">\[
\begin{align*}
    A_1 = 0 &amp;: f(\textbf{x}) = \beta_0 + \beta_1 x \\
    A_1 = 1 &amp;: f(\textbf{x}) = \beta_0 + \beta_1 x + \beta_2 A_1
\end{align*}
\]</span></p>
<p>But the value <span class="math inline">\(A_1=0\)</span> corresponds to <span class="math inline">\(A_2 = 1\)</span>. The simple linear regression <span class="math inline">\(\beta_0 + \beta_1 x\)</span> is the response for the case where <span class="math inline">\(A_2 = 1\)</span>. The coefficient <span class="math inline">\(\beta_2\)</span> now measures the difference between the two levels of <span class="math inline">\(A\)</span>, with <span class="math inline">\(A = 2\)</span> serving as the reference level. The model has two intercepts, one for <span class="math inline">\(A=1\)</span>, and one for <span class="math inline">\(A=2\)</span>, their values are <span class="math inline">\(6.5 - 3 = 3.5\)</span> and <span class="math inline">\(6.5\)</span>, respectively.</p>
<p>You can also see this from the coefficient estimate in the <code>R</code> output: the sample mean of <span class="math inline">\(Y\)</span> when <span class="math inline">\(A = 1\)</span> is <span class="math inline">\(\overline{y}_{A=1} = 3\)</span> and <span class="math inline">\(\overline{y}_{A=2} = 6\)</span>. Their difference is <span class="math inline">\(\widehat{\beta}_2 = -3\)</span>.</p>
<p>If the first level is chosen as the reference level, this estimate has the opposite sign:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">y=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>),</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">x=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="fl">0.5</span>,<span class="fl">0.25</span>,<span class="dv">1</span>,<span class="fl">0.5</span>,<span class="fl">0.25</span>),</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">A=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>A <span class="ot">&lt;-</span> <span class="fu">relevel</span>(<span class="fu">as.factor</span>(df<span class="sc">$</span>A),<span class="at">ref=</span><span class="dv">1</span>)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x <span class="sc">+</span> A, <span class="at">data=</span>df)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error  t value     Pr(&gt;|t|)
(Intercept)  3.500000  0.2089277 16.75220 0.0004631393
x           -2.571429  0.2857143 -9.00000 0.0028958122
A2           3.000000  0.1781742 16.83746 0.0004561983</code></pre>
</div>
</div>
<p><span class="math inline">\(A=1\)</span> now serves as the reference level and the coefficient associated with <code>A2</code> is the difference between the intercept at <span class="math inline">\(A=2\)</span> and at <span class="math inline">\(A=1\)</span>. The absolute intercepts of the two level remain the same, <span class="math inline">\(3.5\)</span> for <span class="math inline">\(A=1\)</span> and <span class="math inline">\(3.5 + 3 = 6.5\)</span> for <span class="math inline">\(A=2\)</span>.</p>
<p>When a factor has more than two levels, reference levels in one-hot encoding works the same way, the effects of all levels is expressed as the difference of the level with respect to the reference level.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p>If a statistical model contains factors and you interpret the coefficient estimates, you must make sure to understand the encoding method–including level ordering and reference levels—otherwise you might draw wrong conclusions about the effects in the model.</p>
<p>When making predictions, the choice of order and reference level does not matter, predictions are invariant, as you can easily verify in the example above.</p>
</div>
</div>
<p>The issue of a singular cross-product matrix <span class="math inline">\(\textbf{X}^\prime\textbf{X}\)</span> could have been prevented in the model with <span class="math inline">\(X\)</span> and <span class="math inline">\(A\)</span> by dropping the intercept. This model has a full-rank <span class="math inline">\(\textbf{X}\)</span> matrix <span class="math display">\[
\textbf{X} = \left [\begin{array}{rrr}
1    &amp; 1 &amp; 0 \\
0.5  &amp; 1 &amp; 0 \\
0.25 &amp; 1 &amp; 0 \\
1    &amp; 0 &amp; 1 \\
0.5  &amp; 0 &amp; 1 \\
0.25 &amp; 0 &amp; 1 \\
\end{array} \right]
\]</span></p>
<p>Even without an intercept, the problem resurfaces as soon as another factor enters the model. Suppose we now add <span class="math inline">\(B\)</span> in one-hot encoding to the model. The <span class="math inline">\(\textbf{X}\)</span> matrix gets three more columns:</p>
<p><span class="math display">\[
\textbf{X} = \left [\begin{array}{rrrrrr}
1    &amp; 1 &amp; 0 &amp; 1 &amp; 0 &amp; 0\\
0.5  &amp; 1 &amp; 0 &amp; 0 &amp; 1 &amp; 0\\
0.25 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; 1\\
1    &amp; 0 &amp; 1 &amp; 1 &amp; 0 &amp; 0\\
0.5  &amp; 0 &amp; 1 &amp; 0 &amp; 1 &amp; 0\\
0.25 &amp; 0 &amp; 1 &amp; 0 &amp; 0 &amp; 1\\
\end{array} \right]
\]</span></p>
<p>Again, we end up with perfect linear dependencies among the columns. The sum of columns 2–3 equals the sum of columns 4–6. It is thus customary to not drop the intercept when factors are present in the model.</p>
</section>
<section id="average-effect-encoding" class="level4">
<h4 class="anchored" data-anchor-id="average-effect-encoding">Average effect encoding</h4>
<p>An encoding that avoids the singularity issue creates only <span class="math inline">\(k-1\)</span> columns from the <span class="math inline">\(k\)</span> levels of the factor and expresses the effect of the levels as differences in the effects from the average effect across all levels. This encoding also relies on the choice of a reference level. Suppose we apply average effect encoding to <span class="math inline">\(B\)</span> and choose <span class="math inline">\(B=3\)</span> as the reference level.</p>
<table class="table-striped table">
<caption>Average effect encoding for <span class="math inline">\(B\)</span> with reference level <span class="math inline">\(B=3\)</span>.</caption>
<thead>
<tr class="header">
<th style="text-align: right;">B</th>
<th style="text-align: right;"><span class="math inline">\(B_1\)</span></th>
<th style="text-align: right;"><span class="math inline">\(B_2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><strong>1</strong></td>
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>2</strong></td>
<td style="text-align: right;"><span class="math inline">\(0\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>3</strong></td>
<td style="text-align: right;"><span class="math inline">\(-1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-1\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>1</strong></td>
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>2</strong></td>
<td style="text-align: right;"><span class="math inline">\(0\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>3</strong></td>
<td style="text-align: right;"><span class="math inline">\(-1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-1\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="baseline-encoding" class="level4">
<h4 class="anchored" data-anchor-id="baseline-encoding">Baseline encoding</h4>
<p>In this encoding, <span class="math inline">\(k-1\)</span> columns are created for the <span class="math inline">\(k\)</span> levels of the factor. The first level is taken as the baseline and the effects are expressed in terms of differences between successive levels. Baseline encoding of <span class="math inline">\(B\)</span> results in the following encoding:</p>
<table class="table-striped table">
<caption>Baseline encoding for <span class="math inline">\(B\)</span> with reference level <span class="math inline">\(B=3\)</span>.</caption>
<thead>
<tr class="header">
<th style="text-align: right;">B</th>
<th style="text-align: right;"><span class="math inline">\(B_1\)</span></th>
<th style="text-align: right;"><span class="math inline">\(B_2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><strong>1</strong></td>
<td style="text-align: right;"><span class="math inline">\(0\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>2</strong></td>
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>3</strong></td>
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>1</strong></td>
<td style="text-align: right;"><span class="math inline">\(0\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>2</strong></td>
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>3</strong></td>
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
</tr>
</tbody>
</table>
<div class="example">
<div class="example-header">
<p>Example: Baseline and Average Encoding</p>
</div>
<div class="example-container">
<p>For our little data set, we compute the baseline and average effect encoding here. Before doing so, let’s fit a model with factor <span class="math inline">\(B\)</span>, and without intercept. The coefficients associated with <span class="math inline">\(B\)</span> are the raw effects of the three levels of <span class="math inline">\(B\)</span>. The intercept is automatically added in model formula expressions in <code>R</code>. You can remove it with <code>-1</code> from the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">y=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>),</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">x=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="fl">0.5</span>,<span class="fl">0.25</span>,<span class="dv">1</span>,<span class="fl">0.5</span>,<span class="fl">0.25</span>),</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">A=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>),</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">B=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>modB <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="fu">as.factor</span>(B) <span class="sc">-</span><span class="dv">1</span>, <span class="at">data=</span>df)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(modB))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error  t value   Pr(&gt;|t|)
as.factor(B)1      2.5        1.5 1.666667 0.19417135
as.factor(B)2      3.5        1.5 2.333333 0.10183797
as.factor(B)3      4.5        1.5 3.000000 0.05766889</code></pre>
</div>
</div>
<p>The coefficients of the factor effects are <span class="math inline">\(\widehat{\beta}_{B1} =\)</span> 2.5, <span class="math inline">\(\widehat{\beta}_{B2} =\)</span> 3.5, and <span class="math inline">\(\widehat{\beta}_{B3} =\)</span> 4.5.</p>
<p>Next we fit the model using baseline encoding for <span class="math inline">\(B\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>),<span class="at">nrow=</span><span class="dv">6</span>,<span class="at">ncol=</span><span class="dv">2</span>)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>modB_baseline <span class="ot">&lt;-</span> <span class="fu">lm</span>(df<span class="sc">$</span>y <span class="sc">~</span> X)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(modB_baseline))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error   t value  Pr(&gt;|t|)
(Intercept)      2.5    1.50000 1.6666667 0.1941713
X1               1.0    2.12132 0.4714045 0.6695150
X2               1.0    2.12132 0.4714045 0.6695150</code></pre>
</div>
</div>
<p>The <code>(Intercept)</code> of this model represents the level <span class="math inline">\(B=1\)</span>, <code>X1</code> is the difference of level <span class="math inline">\(B=2\)</span> to level <span class="math inline">\(B=1\)</span> and <code>X2</code> measures the difference between <span class="math inline">\(B=3\)</span> and <span class="math inline">\(B=2\)</span>.</p>
<p>If <span class="math inline">\(B\)</span> is expressed in average effect encoding we obtain the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>),<span class="at">nrow=</span><span class="dv">6</span>,<span class="at">ncol=</span><span class="dv">2</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>modB_ave_eff <span class="ot">&lt;-</span> <span class="fu">lm</span>(df<span class="sc">$</span>y <span class="sc">~</span> X)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(modB_ave_eff))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Estimate Std. Error       t value   Pr(&gt;|t|)
(Intercept)  3.500000e+00  0.8660254  4.041452e+00 0.02726185
X1          -1.000000e+00  1.2247449 -8.164966e-01 0.47402139
X2          -2.110977e-16  1.2247449 -1.723605e-16 1.00000000</code></pre>
</div>
</div>
<p>We see from the initial analysis that the average effect of <span class="math inline">\(B\)</span> is <span class="math inline">\(1/3 \times (2.5+3.5+4.5) = 3.5\)</span>. The <code>(Intercept)</code> estimate represents this average in the average effect encoding. <code>X1</code> and <code>X2</code> represent the differences of <span class="math inline">\(B=1\)</span> and <span class="math inline">\(B=2\)</span> from the average. If we place the <span class="math inline">\(-1\)</span> row at level <span class="math inline">\(B=2\)</span>, then <code>X1</code> and <code>X2</code> are the differences of <span class="math inline">\(B=1\)</span> and <span class="math inline">\(B=3\)</span> from the average effect of <span class="math inline">\(B\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>),<span class="at">nrow=</span><span class="dv">6</span>,<span class="at">ncol=</span><span class="dv">2</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>modB_ave_eff <span class="ot">&lt;-</span> <span class="fu">lm</span>(df<span class="sc">$</span>y <span class="sc">~</span> X2)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(modB_ave_eff))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error    t value   Pr(&gt;|t|)
(Intercept)      3.5  0.8660254  4.0414519 0.02726185
X21             -1.0  1.2247449 -0.8164966 0.47402139
X22              1.0  1.2247449  0.8164966 0.47402139</code></pre>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="continuous-variables" class="level3">
<h3 class="anchored" data-anchor-id="continuous-variables">Continuous Variables</h3>
<p>Why would you encode continuous variables, they are already in numerical form?</p>
<p>Suppose you are modeling a target as a function of time and the measurements are taken in minute intervals. Maybe such a granular resolution is not necessary and you are more interested in seasonal or annual trends. You can convert the time measurements easily into months, seasons, or years, using date-time functions in the software. Should you now treat the converted values as continuous measurements or as categories of a factor?</p>
<p>When working with age variables we sometimes collect them into age groups. Age groups <code>0-9 years</code>, <code>10-24 years</code>, and <code>25-40 years</code> are not evenly spaced and are no longer continuous. Age has been <strong>discretized</strong> into a factor variable. Other terms used for the process of discretizing continuous variables are <strong>binning</strong> and <strong>quantizing</strong>.</p>
<p>The advantage of using factors instead of the continuous values lies in the introduction of nonlinear relationships while maintaining interpretability. If you model <code>age</code> as a continuous variable, then <span class="math display">\[
Y = \beta_0 + \beta_1 \text{age} + \cdots + \epsilon
\]</span> implies a linear relationship between age and the target. Binning age into three groups, on the other hand, leads to the model <span class="math display">\[
Y = \beta_0 + \beta_1\text{[Age=0-9]} + \beta_2\text{[Age=10-24]} + \beta_3\text{[Age=25-40]} + \cdots + \epsilon
\]</span> This model allows for different effects in the age groups.</p>
<p>To bin continuous numeric variables in <code>R</code> you can use the <code>cut()</code> function in the <code>base</code> package or the <code>ntile</code> function in <code>dplyr</code>. <code>ntile</code> is a rough ranking of the <span class="math inline">\(n\)</span> observations from smallest to largest, and then bucketing into <code>k</code> groups of roughly equal <strong>size</strong>. <code>cut</code> takes a numeric vector and also bins it into <code>k</code> groups of equal <strong>width</strong>. You can supply a a vector of break points to <code>cut</code> which makes it a good choice to bin values by, say, quantiles of the distribution.</p>
<p>The following code bins the variable <code>x</code> into 5 categories using <code>ntile</code>. The result of the operation is an integer that indicates which category (from smallest to largest) the observation belongs to.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x=</span><span class="fu">rnorm</span>(<span class="dv">200</span>,<span class="at">mean=</span><span class="dv">3</span>,<span class="at">sd=</span><span class="dv">2</span>))</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>df_binned <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">x_binned =</span> <span class="fu">ntile</span>(x, <span class="at">n=</span><span class="dv">5</span>))</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_binned)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           x x_binned
1  4.6583277        4
2 -0.3390924        1
3  3.5221325        3
4  4.3559987        4
5  3.1060334        3
6  3.2046656        3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df_binned<span class="sc">$</span>x_binned)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 1  2  3  4  5 
40 40 40 40 40 </code></pre>
</div>
</div>
<p><code>cut</code> creates by default character labels that indicate the lower and upper value of the bins. Setting <code>labels=FALSE</code> results in integer values for the categories</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>x_cut <span class="ot">&lt;-</span> <span class="fu">cut</span>(df<span class="sc">$</span>x,<span class="at">breaks=</span><span class="dv">5</span>)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>x_cut_int <span class="ot">&lt;-</span> <span class="fu">cut</span>(df<span class="sc">$</span>x,<span class="at">breaks=</span><span class="dv">5</span>,<span class="at">labels=</span><span class="cn">FALSE</span>)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           x         x_cut x_cut_int
1  4.6583277   (4.22,6.19]         4
2 -0.3390924 (-1.69,0.288]         1
3  3.5221325   (2.26,4.22]         3
4  4.3559987   (4.22,6.19]         4
5  3.1060334   (2.26,4.22]         3
6  3.2046656   (2.26,4.22]         3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>x_cut)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
(-1.69,0.288]  (0.288,2.26]   (2.26,4.22]   (4.22,6.19]   (6.19,8.17] 
           23            48            63            55            11 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>x_cut_int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 1  2  3  4  5 
23 48 63 55 11 </code></pre>
</div>
</div>
<p>The results of <code>ntile</code> and <code>cut</code> are very different: <code>ntile</code> divides the range of X into intervals of <strong>equal number</strong> of observations, whereas <code>cut</code> divides the range into intervals of <strong>equal width</strong>.</p>
<p>You can make <code>cut</code> use equal number of observations by supplying a vector of breaks that corresponds to percentiles of the distribution of the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>qt <span class="ot">&lt;-</span> <span class="fu">quantile</span>(df<span class="sc">$</span>x,<span class="at">probs=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="fl">0.2</span>))</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>qt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       0%       20%       40%       60%       80%      100% 
-1.679191  1.380707  2.542361  3.811501  4.931641  8.156516 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>x_cut_qt <span class="ot">&lt;-</span> <span class="fu">cut</span>(df<span class="sc">$</span>x,<span class="at">breaks=</span>qt,</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">include.lowest=</span><span class="cn">TRUE</span>)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           x         x_cut x_cut_int     x_cut_qt
1  4.6583277   (4.22,6.19]         4  (3.81,4.93]
2 -0.3390924 (-1.69,0.288]         1 [-1.68,1.38]
3  3.5221325   (2.26,4.22]         3  (2.54,3.81]
4  4.3559987   (4.22,6.19]         4  (3.81,4.93]
5  3.1060334   (2.26,4.22]         3  (2.54,3.81]
6  3.2046656   (2.26,4.22]         3  (2.54,3.81]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>x_cut_qt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
[-1.68,1.38]  (1.38,2.54]  (2.54,3.81]  (3.81,4.93]  (4.93,8.16] 
          40           40           40           40           40 </code></pre>
</div>
</div>
</section>
</section>
<section id="transforming-the-target" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="transforming-the-target"><span class="header-section-number">5.4</span> Transforming the Target</h2>
<p>The previously discussed preprocessing steps can be applied to any variable, input or target variable.</p>
<p>The purpose of transforming the target variable is to meet distributional assumptions of the analysis. For example, many statistical estimators have particularly nice properties when the data are Gaussian distributed. A common transformation of <span class="math inline">\(Y\)</span> is thus to morph its distribution so that the transformed <span class="math inline">\(Y^*\)</span> is closer to Gaussian distributed than <span class="math inline">\(Y\)</span>. Sometimes transformations just aim to create more symmetry or to stabilize the variance across groups of observations. Transformations change the relationship between (transformed) target and the inputs, it is common to transform targets to a scale where effect are linear. We can then model additive effects on the transformed scale instead of complex nonlinear effects on the original scale of the data.</p>
<section id="discretizing" class="level3">
<h3 class="anchored" data-anchor-id="discretizing">Discretizing</h3>
<p>Discretizing a continuous target variable is commonly done to classify the target. If observations are taken with measurement error, we might not be confident in the measured values but we are comfortable classifying an outcome as <em>high</em> or <em>low</em> based on a threshold for <span class="math inline">\(Y\)</span> and model the transformed data using logistic regression.</p>
</section>
<section id="nonlinear-transformations" class="level3">
<h3 class="anchored" data-anchor-id="nonlinear-transformations">Nonlinear Transformations</h3>
<p>Nonlinear transformations of a continuous target variable apply functions to modify the distributional properties. A common device to transform right-skewed distributions (long right tail) of positive values is to take logarithms or square roots. If <span class="math inline">\(Y\)</span> has a <strong>log-normal</strong> distribution, then the log transformation yields a Gaussian random variable.</p>
<p>A random variable <span class="math inline">\(Y\)</span> has a log-normal distribution with parameters <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> if its p.d.f. is given by <span class="math display">\[
p(y) = \frac{1}{y\sqrt{2\pi\beta}}\exp\left\{-\frac{(\log y - \alpha)^2}{2\beta} \right\}, \qquad y &gt; 0
\]</span> <span class="math inline">\(Y\)</span> has mean <span class="math inline">\(\mu = \exp\{\alpha + \beta/2\}\)</span> and variance <span class="math inline">\(\sigma^2 = (e^\beta - 1) \exp\{2\alpha + \beta\}\)</span>. If <span class="math inline">\(Y \sim \text{Lognormal}(\alpha,\beta)\)</span>, then <span class="math inline">\(\log Y\)</span> has a Gaussian distribution with mean <span class="math inline">\(\alpha\)</span> and variance <span class="math inline">\(\beta\)</span>. We can also construct a log-normal variable from a standard Gaussian: if <span class="math inline">\(Z \sim G(0,1)\)</span>, then <span class="math inline">\(Y = \exp\{\alpha + \beta Z\}\)</span> has a log-normal distribution. <a href="#fig-lognormal" class="quarto-xref">Figure&nbsp;<span>5.4</span></a> shows the histogram of 1,000 random samples from a Lognormal(2,1/2) distribution and the histogram of the log-transformed values.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-lognormal" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lognormal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="featproc_files/figure-html/fig-lognormal-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lognormal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.4: Histograms of 1,000 random samples from <span class="math inline">\(Y \sim \text{Lognormal}(2,1/2)\)</span> and of <span class="math inline">\(\log Y\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<section id="box-cox-family" class="level4">
<h4 class="anchored" data-anchor-id="box-cox-family">Box-Cox family</h4>
<p>The Box-Cox family of transformations is a special case of <strong>power transformations</strong> that was introduced by <span class="citation" data-cites="BoxCox1964">Box and Cox (<a href="references.html#ref-BoxCox1964" role="doc-biblioref">1964</a>)</span>. The goal of the transformation is to stabilize the variance and to make the data more Gaussian distributed.</p>
<p>Most commonly used is the one-parameter version of the Box-Cox transformation <span id="eq-box-cox1"><span class="math display">\[
y^{(\lambda)} = \left \{
\begin{array}{ll}
\frac{y^\lambda - 1}{\lambda} &amp; \text{if } \lambda \ne 0 \\
\log y &amp; \text{if } \lambda = 0
\end{array}\right.
\tag{5.2}\]</span></span></p>
<p>This transformation applies if <span class="math inline">\(y &gt; 0\)</span>. For the more general case, <span class="math inline">\(y &gt; -c\)</span>, the two-parameter Box-Cox transformation can be used <span class="math display">\[
y^{(\lambda)} = \left \{
\begin{array}{ll}
\frac{(y+c)^\lambda - 1}{\lambda} &amp; \text{if } \lambda \ne 0 \\
\log (y+c) &amp; \text{if } \lambda = 0
\end{array}\right.
\]</span></p>
<p><span class="math inline">\(c\)</span> is simply a value by which to shift the distribution so that <span class="math inline">\(y+c &gt; 0\)</span>. The key parameter in the Box-Cox transformation is <span class="math inline">\(\lambda\)</span>.</p>
<p>The term <span class="math inline">\(-\: 1\)</span> in the numerator and the division by <span class="math inline">\(\lambda\)</span> for <span class="math inline">\(\lambda \ne 0\)</span> in <a href="#eq-box-cox1" class="quarto-xref">Equation&nbsp;<span>5.2</span></a> are linear operations that do not affect the proximity to normality of <span class="math inline">\(y^{(\lambda)}\)</span>. An abbreviated version of <a href="#eq-box-cox1" class="quarto-xref">Equation&nbsp;<span>5.2</span></a> is</p>
<p><span id="eq-box-cox3"><span class="math display">\[
y^{(\lambda)} = \left \{
\begin{array}{ll}
y^\lambda &amp; \text{if } \lambda \ne 0 \\
\log y    &amp; \text{if } \lambda = 0
\end{array}\right.
\tag{5.3}\]</span></span></p>
<p>For a given value of <span class="math inline">\(\lambda\)</span>, the transformation is monotonic, mapping large values to large values if <span class="math inline">\(\lambda &gt; 0\)</span> and large values to small values if <span class="math inline">\(\lambda &lt; 0\)</span>. The transformation thus retains the ordering of observations (<a href="#fig-boxcox-transforms" class="quarto-xref">Figure&nbsp;<span>5.5</span></a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-boxcox-transforms" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxcox-transforms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="featproc_files/figure-html/fig-boxcox-transforms-1.png" class="lightbox" data-glightbox="description: .lightbox-desc-1" data-gallery="quarto-lightbox-gallery-1"><img src="featproc_files/figure-html/fig-boxcox-transforms-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxcox-transforms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.5: Box-Cox transformations for various values of <span class="math inline">\(\lambda\)</span>
</figcaption>
</figure>
</div>
</div>
</div>
<p>How do we find <span class="math inline">\(\lambda\)</span>? If the assumption is that for some value <span class="math inline">\(\widehat{\lambda}\)</span> the distribution of <span class="math inline">\(y^{(\widehat{\lambda})}\)</span> is Gaussian, then <span class="math inline">\(\lambda\)</span> can be estimated by maximum likelihood assuming a Gaussian distribution–after all, we are looking for the value of <span class="math inline">\(\lambda\)</span> for which the Gaussian likelihood of the transformed data is highest.</p>
<p>The following code applies the Box-Cox transformation to a random sample from a Gamma(3,2) distribution</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">6465</span>)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x=</span><span class="fu">rgamma</span>(<span class="dv">1000</span>,<span class="dv">3</span>,<span class="dv">2</span>))</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>df_bc <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">preProcess</span>(df,<span class="at">method=</span><span class="st">"BoxCox"</span>)</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>df_bc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Created from 1000 samples and 1 variables

Pre-processing:
  - Box-Cox transformation (1)
  - ignored (0)

Lambda estimates for Box-Cox transformation:
0.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>df_bc_data <span class="ot">&lt;-</span> <span class="fu">predict</span>(df_bc,df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The estimate of the <span class="math inline">\(\lambda\)</span> parameter is 0.3.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(df<span class="sc">$</span>x,<span class="at">main=</span><span class="st">"Original"</span>,<span class="at">xlab=</span><span class="st">""</span>)</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(df_bc_data<span class="sc">$</span>x, <span class="at">main=</span><span class="st">"BoxCox(0.3)"</span>,<span class="at">xlab=</span><span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-gamma-boxcox" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gamma-boxcox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="featproc_files/figure-html/fig-gamma-boxcox-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gamma-boxcox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.6: Original and Box-Cox-transformed data drawn from a Gamma(3,2) distribution.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="quantile-transformation" class="level4">
<h4 class="anchored" data-anchor-id="quantile-transformation">Quantile transformation</h4>
<p>The Box-Cox transformation does a good job to transform the data closer to a Gaussian distribution in the previous examples. It is not fail safe, however. Data that appear uniform or data with multiple modes do not transform to normality easily with the Box-Cox family.</p>
<p>However, a transformation based on the quantiles of the observed data can achieve this. In fact, you can use quantiles to generate data from any distribution.</p>
<p>If <span class="math inline">\(Y\)</span> is a random variable with c.d.f. <span class="math inline">\(F(y) = \Pr(Y \le y)\)</span>, then the quantile function <span class="math inline">\(Q(p)\)</span> is the inverse of the cumulative distribution function; for a given probability <span class="math inline">\(p\)</span>, it returns the value <span class="math inline">\(y\)</span> for which <span class="math inline">\(F(y) = p\)</span>.</p>
<p>Now here is a possibly surprising result: if <span class="math inline">\(Y\)</span> has c.d.f. <span class="math inline">\(F(y)\)</span>, then we can think of the c.d.f as a transformation of <span class="math inline">\(Y\)</span>. What would its distribution look like? The following code draws 1,000 samples from a G(<span class="math inline">\(2,1.5^2\)</span>) distribution and plots the histogram of the c.d.f. values <span class="math inline">\(F(y)\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">45</span>)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>yn <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>,<span class="at">mean=</span><span class="dv">2</span>,<span class="at">sd=</span><span class="fl">1.5</span>)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>F_yn <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(yn,<span class="at">mean=</span><span class="dv">2</span>,<span class="at">sd=</span><span class="fl">1.5</span>)    </span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(F_yn,<span class="at">main=</span><span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="featproc_files/figure-html/normquant-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>The distribution of <span class="math inline">\(F(y)\)</span> is <strong>uniform</strong> on (0,1)—this is true for any distribution, not just the Gaussian.</p>
<p>We can combine this result with the following, possibly also surprising, result: If <span class="math inline">\(U\)</span> is a uniform random variable, and <span class="math inline">\(Q(p)\)</span> is the quantile function of <span class="math inline">\(Y\)</span>, then <span class="math inline">\(Q(u)\)</span> has the same distribution as <span class="math inline">\(Y\)</span>. This is how you can generate random numbers from any distribution if you have a generator of uniform random numbers: plug the uniform random numbers into the quantile function.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>norm_rv <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fu">runif</span>(<span class="dv">1000</span>),<span class="at">mean=</span><span class="dv">2</span>,<span class="at">sd=</span><span class="fl">1.5</span>)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(norm_rv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="featproc_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>These are the key results behind <strong>quantile transformation</strong>, mapping one distribution to another based on quantiles.</p>
<p>The <code>QuantileTransformer</code> in <code>sklearn.preprocessing</code> can transform data based on quantiles to a uniform (default) or a Gaussian distribution. The results of transformation to normality for the Gamma(3,2) data are shown in <a href="#fig-gamma-quantile" class="quarto-xref">Figure&nbsp;<span>5.7</span></a>. These are not very different from the results of the Box-Cox transformation. However, the quantile transformation method always works, even in cases where the Box-Cox family of transformation fails to get close to normality.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn <span class="im">import</span> preprocessing</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">234</span>)</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>x1 <span class="op">=</span> np.random.gamma(shape<span class="op">=</span><span class="dv">3</span>,scale<span class="op">=</span><span class="dv">2</span>,size<span class="op">=</span><span class="dv">1000</span>)</span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>x1 <span class="op">=</span> np.reshape(x1,(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a>quantizer <span class="op">=</span> preprocessing.QuantileTransformer(</span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a>    output_distribution<span class="op">=</span><span class="st">'normal'</span>)</span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a>x1_trans <span class="op">=</span> quantizer.fit_transform(x1)</span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-15"><a href="#cb74-15" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb74-16"><a href="#cb74-16" aria-hidden="true" tabindex="-1"></a>plt.hist(x1,bins<span class="op">=</span><span class="dv">20</span>,color<span class="op">=</span><span class="st">'0.7'</span>,alpha<span class="op">=</span><span class="fl">0.7</span>,label<span class="op">=</span><span class="st">'Original'</span>)</span>
<span id="cb74-17"><a href="#cb74-17" aria-hidden="true" tabindex="-1"></a>plt.hist(x1_trans,color<span class="op">=</span><span class="st">'magenta'</span>,alpha<span class="op">=</span><span class="fl">0.5</span>,label<span class="op">=</span><span class="st">'Quantile transformed'</span>)</span>
<span id="cb74-18"><a href="#cb74-18" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb74-19"><a href="#cb74-19" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-gamma-quantile" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gamma-quantile-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="featproc_files/figure-html/fig-gamma-quantile-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gamma-quantile-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.7: Quantile transformation to normality for Gamma(3,2) data.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="to-transform-or-not-to-transform" class="level4">
<h4 class="anchored" data-anchor-id="to-transform-or-not-to-transform">To Transform or not to Transform</h4>
<p>Why do we not always apply a nonlinear transform to a continuous target variable to achieve greater symmetry, stable variance, greater normality? After all, the results of the transformations are impressive. <a href="#fig-bimodal-quantile" class="quarto-xref">Figure&nbsp;<span>5.8</span></a> shows a quantile transformation to normality for data from a two-component mixture of Gamma densities. The bimodal distribution maps to a standard Gaussian like magic.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-bimodal-quantile" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bimodal-quantile-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="featproc_files/figure-html/fig-bimodal-quantile-3.png" class="lightbox" data-glightbox="description: .lightbox-desc-2" data-gallery="quarto-lightbox-gallery-2"><img src="featproc_files/figure-html/fig-bimodal-quantile-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bimodal-quantile-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.8: Quantile transformation to normality for bimodal data from a mixture distribution.
</figcaption>
</figure>
</div>
</div>
</div>
<p>What are you giving up by analyzing the transformed target instead of the original target?</p>
<p>When the goal of data analytics is testing research hypotheses, we usually observe the target variable of interest and formulate hypotheses about its properties. What do these hypotheses mean in terms of the transformed data? This is not always clear, in particular when highly nonlinear transformations such as quantiles are involved.</p>
<p>The parameters of the distribution of <span class="math inline">\(Y^*\)</span>, the transformed target, are not estimating the parameters of the distribution of <span class="math inline">\(Y\)</span>. The mean of <span class="math inline">\(\log Y\)</span> is not the log of the mean of <span class="math inline">\(Y\)</span>. When the transformation can be inverted, we usually end up with biased estimators. For example, if <span class="math inline">\(Y\)</span> has a Lognormal(<span class="math inline">\(\alpha,\beta\)</span>) distribution, then <span class="math inline">\(\overline{Y}\)</span> is an unbiased estimate of <span class="math display">\[
\text{E}[Y] = \exp\{\alpha + \beta/2\}
\]</span></p>
<p>If we log-transform the data the sample mean of the transformed data <span class="math inline">\(y^* = \log y\)</span> estimates <span class="math display">\[
\text{E}[\overline{Y}^*] = \frac{1}{n}\sum_{i=1}^n \text{E}[\log Y_i]
\]</span> The exponentiation of this estimator is not an unbiased estimator of <span class="math inline">\(\text{E}[Y]\)</span>.</p>


<div class="hidden" aria-hidden="true">
<span class="glightbox-desc lightbox-desc-1">Figure&nbsp;5.5: Box-Cox transformations for various values of <span class="math inline">\(\lambda\)</span></span>
<span class="glightbox-desc lightbox-desc-2">Figure&nbsp;5.8: Quantile transformation to normality for bimodal data from a mixture distribution.</span>
</div>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-BoxCox1964" class="csl-entry" role="listitem">
Box, G. E. P., and D. R. Cox. 1964. <span>“An Analysis of Transformations.”</span> <em>Journal of the Royal Statistical Society. Series B (Methodological)</em> 26 (2): 211–52. <a href="http://www.jstor.org/stable/2984418">http://www.jstor.org/stable/2984418</a>.
</div>
</div>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./wrangling_data.html" class="pagination-link" aria-label="Wrangling Data">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Wrangling Data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./summarization.html" class="pagination-link" aria-label="Summarization">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summarization</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Statistical Programming by Oliver Schabenberger</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"loop":false,"closeEffect":"zoom","selector":".lightbox","openEffect":"zoom","descPosition":"bottom"});
window.onload = () => {
  lightboxQuarto.on('slide_before_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    const href = trigger.getAttribute('href');
    if (href !== null) {
      const imgEl = window.document.querySelector(`a[href="${href}"] img`);
      if (imgEl !== null) {
        const srcAttr = imgEl.getAttribute("src");
        if (srcAttr && srcAttr.startsWith("data:")) {
          slideConfig.href = srcAttr;
        }
      }
    } 
  });

  lightboxQuarto.on('slide_after_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    if (window.Quarto?.typesetMath) {
      window.Quarto.typesetMath(slideNode);
    }
  });

};
          </script>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>